/* tslint:disable */
/* eslint-disable */
/**
 * RestApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResult
 */
export interface AuthResult {
    /**
     * 
     * @type {boolean}
     * @memberof AuthResult
     */
    result?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResult
     */
    errors?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    token?: string | null;
}

export function AuthResultFromJSON(json: any): AuthResult {
    return AuthResultFromJSONTyped(json, false);
}

export function AuthResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : json['result'],
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function AuthResultToJSON(value?: AuthResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result,
        'errors': value.errors,
        'token': value.token,
    };
}

