/* tslint:disable */
/* eslint-disable */
/**
 * RestApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimRequest
 */
export interface ClaimRequest {
    /**
     * 
     * @type {string}
     * @memberof ClaimRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimRequest
     */
    claimKey: string;
    /**
     * 
     * @type {string}
     * @memberof ClaimRequest
     */
    claimValue: string;
}

export function ClaimRequestFromJSON(json: any): ClaimRequest {
    return ClaimRequestFromJSONTyped(json, false);
}

export function ClaimRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'claimKey': json['claimKey'],
        'claimValue': json['claimValue'],
    };
}

export function ClaimRequestToJSON(value?: ClaimRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'claimKey': value.claimKey,
        'claimValue': value.claimValue,
    };
}

