/* tslint:disable */
/* eslint-disable */
/**
 * RestApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemperatureData
 */
export interface TemperatureData {
    /**
     * 
     * @type {number}
     * @memberof TemperatureData
     */
    temperature?: number;
    /**
     * 
     * @type {string}
     * @memberof TemperatureData
     */
    day?: string | null;
}

export function TemperatureDataFromJSON(json: any): TemperatureData {
    return TemperatureDataFromJSONTyped(json, false);
}

export function TemperatureDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemperatureData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'temperature': !exists(json, 'temperature') ? undefined : json['temperature'],
        'day': !exists(json, 'day') ? undefined : json['day'],
    };
}

export function TemperatureDataToJSON(value?: TemperatureData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'temperature': value.temperature,
        'day': value.day,
    };
}

